services:
  back:
    build: .
    container_name: quiz-back-container
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: on-failure:3
    networks:
      - public_network
  db:
    image: postgres:17-alpine
    container_name: quiz-db-postgres
    restart: always
    volumes:
      - quizData:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "2543:5432"
    networks:
      - public_network


volumes:
  quizData:

networks:
  public_network:
